version: '3'
services:
  react-app:
    build: react-app
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    volumes:
      - ./react-app:/react-app
  graphql-server:
    build: graphql-server
    ports:
      - '4000:4000'
    tty: true
    stdin_open: true
    volumes:
      - ./graphql-server:/graphql-server
